/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nitro V
 */
public class TransactionManagerUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionManagerUI.class.getName());

    /**
     * Creates new form TransactionManagerUI
     */
    public TransactionManagerUI() {
        initComponents();
        populateAccountDropdown(); // Fills our account picker list
        refreshTable();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDeposit = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbAccount = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(105, 0, 0));

        btnDeposit.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnWithdraw.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Viner Hand ITC", 1, 20)); // NOI18N
        btnView.setText("View History");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Account ID:");

        cmbAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Amount:");

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Account ID", "Type", "Amount", "Date"
            }
        ));
        jScrollPane1.setViewportView(transactionTable);

        jLabel3.setFont(new java.awt.Font("Vivaldi", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Transaction");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnWithdraw)
                        .addGap(18, 18, 18)
                        .addComponent(btnView))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel3)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWithdraw)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
        String accountId = (String) cmbAccount.getSelectedItem();
String amountStr = txtAmount.getText();

if (accountId == null || amountStr.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please select an account and enter an amount.");
    return;
}

double amount = Double.parseDouble(amountStr);

try (java.sql.Connection conn = DBConnection.getConnection()) {
    conn.setAutoCommit(false);
    
    // 1. CHECK CURRENT BALANCE FIRST: See if account has enough funds available
    String checkBalanceSql = "SELECT balance FROM Account WHERE account_id = ?";
    java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkBalanceSql);
    checkStmt.setInt(1, Integer.parseInt(accountId));
    java.sql.ResultSet rs = checkStmt.executeQuery();
    
    if (rs.next()) {
        double currentBalance = rs.getDouble("balance");
        if (currentBalance < amount) {
            // STOP! Block withdrawal due to insufficient funds error
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Insufficient funds! Current balance: $" + currentBalance);
            return;
        }
    }
    
    // 2. DEDUCT MONEY: If they have enough, proceed with balance deduction
    String deductSql = "UPDATE Account SET balance = balance - ? WHERE account_id = ?";
    java.sql.PreparedStatement p1 = conn.prepareStatement(deductSql);
    p1.setDouble(1, amount);
    p1.setInt(2, Integer.parseInt(accountId));
    p1.executeUpdate();
    
    // 3. LOG TRANSACTION HISTORY entry
    String logSql = "INSERT INTO Transaction (account_id, transaction_type, amount, transaction_date) VALUES (?, 'Withdraw', ?, CURDATE())";
    java.sql.PreparedStatement p2 = conn.prepareStatement(logSql);
    p2.setInt(1, Integer.parseInt(accountId));
    p2.setDouble(2, amount);
    p2.executeUpdate();
    
    conn.commit();
    javax.swing.JOptionPane.showMessageDialog(this, "Successfully withdrew $" + amount);
    txtAmount.setText("");
    refreshTable();
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Withdrawal error: " + ex.getMessage());
}
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        String accountId = (String) cmbAccount.getSelectedItem();
String amountStr = txtAmount.getText();

if (accountId == null || amountStr.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please select an account and enter an amount.");
    return;
}

double amount = Double.parseDouble(amountStr);

try (java.sql.Connection conn = DBConnection.getConnection()) {
    conn.setAutoCommit(false); // Safety transaction lock
    
    // 1. Update the Account table by adding the deposit amount to the current balance
    String updateBalanceSql = "UPDATE Account SET balance = balance + ? WHERE account_id = ?";
    java.sql.PreparedStatement p1 = conn.prepareStatement(updateBalanceSql);
    p1.setDouble(1, amount);
    p1.setInt(2, Integer.parseInt(accountId));
    p1.executeUpdate();
    
    // 2. Insert a history log into the Transaction table
    String logTransactionSql = "INSERT INTO Transaction (account_id, transaction_type, amount, transaction_date) VALUES (?, 'Deposit', ?, CURDATE())";
    java.sql.PreparedStatement p2 = conn.prepareStatement(logTransactionSql);
    p2.setInt(1, Integer.parseInt(accountId));
    p2.setDouble(2, amount);
    p2.executeUpdate();
    
    conn.commit(); // Push to DB
    javax.swing.JOptionPane.showMessageDialog(this, "Successfully deposited $" + amount);
    txtAmount.setText("");
    refreshTable();
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Deposit error: " + ex.getMessage());
}
        
    }//GEN-LAST:event_btnDepositActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionManagerUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JComboBox<String> cmbAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable transactionTable;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
// 1. Loads all existing Account IDs into your dropdown selection menu
private void populateAccountDropdown() {
    cmbAccount.removeAllItems();
    String sql = "SELECT account_id FROM Account";
    try (java.sql.Connection conn = DBConnection.getConnection();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery(sql)) {
        
        while (rs.next()) {
            cmbAccount.addItem(rs.getString("account_id"));
        }
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading accounts: " + ex.getMessage());
    }
}

// 2. Loads transaction logs into your table grid view
private void refreshTable() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) transactionTable.getModel();
    model.setRowCount(0); // Wipe old lines
    
    String sql = "SELECT * FROM Transaction";
    try (java.sql.Connection conn = DBConnection.getConnection();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery(sql)) {
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("transaction_id"),
                rs.getInt("account_id"),
                rs.getString("transaction_type"),
                rs.getBigDecimal("amount"),
                rs.getDate("transaction_date")
            });
        }
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading history: " + ex.getMessage());
    }
}
}
